### ISSUE TITLE
Not working behind cloudflare

### ISSUE THREAD

**Issue by petakcm8** [stagas/maptail#21]
Hi,

So I am totally running into despair about this

Have tried everything I can to make it work with a domain in cloudflare (and subdomains for that matter) , but it just won't go.

I have no issues when I setup the host to the server ip and access with that ip on the node server port.

If I change this to anything else it won't work (even localhost)

Tried websockets as suggested and in nginx added proxy_pass to server ip and port but still no go.

Any help would be most appreciated

Also, if I point the domain directly to the ip without using nginx proxy pass I can connect to node server port and I see the map but no data shows up at all.

Thanks

**Comment by stagas** [comment]
I have not tried using it with cloudflare so I have no idea what might be going wrong. My suggestion is to check for any errors in the browser console or the shell and see if there's anything there and maybe paste these here. Also, have you tried it in both Chrome and Firefox?

**Comment by petakcm8** [comment]
Hi and thanks for the fast reply !

I have followed your suggestion and here are the errors I found in browser console :

1) Refused to execute script from 'https://raw.github.com/kriskowal/es5-shim/master/es5-shim.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled

2) WebSocket connection to 'ws://livemap.domain.com:8080/' failed: Error during WebSocket handshake: Unexpected response code: 200 

Uncaught Error: Uncaught, unspecified 'error' event. simpl.js:86EventEmitter.emit simpl.js:86EventStack.emit simpl.js:327client.onerror

When I access the node server ip directly I just get the first error and everything works fine !

**Comment by stagas** [comment]
My guess is something in the pipeline isn't setup to proxy WebSockets properly, cloudflare or nginx. Maybe this will help: https://www.nginx.com/blog/websocket-nginx/

**Comment by petakcm8** [comment]
My Websockets are porperly setup I believe, since I added the right proxy options.

I just googled about websockets with cloudflare and I think that they don't support websockets on the free plans so that is probably it.

I will upgrade my plan today and update on this 

Thanks :)

**Comment by petakcm8** [comment]
Confirmed, issue is on cloudflare side that offers no websocket support for all plans except Business.

If anyone ever goes through the same issue, stop trying :)
